export enum ActionTypes {
  SHOW_LOADER = "SHOW_LOADER",
  SIGN_IN = "SIGN_IN",
  SIGN_OUT = "SIGN_OUT",
  CREATE_EVENT = "CREATE_EVENT",
  UPDATE_EVENT = "UPDATE_EVENT",
  CREATE_APPLICANT = "CREATE_APPLICANT",
  UPDATE_APPLICANT = "UPDATE_APPLICANT",
  FETCH_APPLICANTS = "FETCH_APPLICANTS",
  FETCH_EVENTS = "FETCH_EVENTS",
  FETCH_MORE_EVENTS = "FETCH_MORE_EVENTS",
  FETCH_MORE_APPLICANTS = "FETCH_MORE_APPLICANTS",
}
