export enum ActionTypes {
    SIGN_IN = "SIGN_IN",
    SIGN_OUT = "SIGN_OUT",
    CREATE_EVENT = "CREATE_EVENT",
    UPDATE_EVENT = "UPDATE_EVENT",
    CREATE_APPLICANT = "CREATE_APPLICANT",
    UPDATE_APPLICANT = "UPDATE_APPLICANT",
}
